server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: never
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: pl.piomin.services.organization